### ISSUE TITLE
Data download link

### ISSUE THREAD

**Issue by jhhuang96** [xlwang233/GCRNN#1]
Could you provide "top10_graph.pkl"  and "data/METR-LA" download url ? 

Thanks a lot!

**Comment by xlwang233** [comment]
@jhhuang96 
Hi,
They way of obtaining the METR-LA dataset is well-explained in [liyaguang/DCRNN](https://github.com/liyaguang/DCRNN). As for 'top10_graph', sorry I can't provide it right now mainly because the code is still under development and is far beyond completion. 

Thanks for your intersts
